In [1]:
import torch
import numpy as np

In [3]:
t1 = torch.tensor([1,1,1])

In [4]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


# pytorch: cat vs stack

In [12]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [13]:
torch.cat((t1,t2,t3),dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [14]:
torch.stack((t1,t2,t3),dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

# tensorflow: cat vs stack

tensorflow和pytorch类似，只是cat方法替代为concat方法，dim参数替代为axis，stack同理，tensorflow的expand_dims方法扽沟通与Pytorch的unsqueeze方法

# numpy: cat vs stack

In [15]:
n1 = np.array([1,1,1])
n2 = np.array([2,2,2])
n3 = np.array([3,3,3])

In [10]:
np.concatenate((n1,n2,n3),axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [11]:
np.stack((n1,n2,n3),axis=1)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])